### ISSUE TITLE
`want-osi-do-not-want.svg` is broken on firefox

### ISSUE THREAD

**Issue by iomintz** [kemitchell/writing.kemitchell.com#12]
## Expected appearance
![want-osi-do-not-want.svg, as rendered by GitHub](https://user-images.githubusercontent.com/538336/68924513-a4127680-0746-11ea-8efa-f377ac95dfe7.png)

## Actual appearance
![want-osi-do-not-want.svg, as rendered by FireFox](https://user-images.githubusercontent.com/538336/68924552-b7bddd00-0746-11ea-93c9-0561b862cd80.png)

## Additional information
FireFox 70.0.01 64-bit for Arch Linux, using Xorg

**Comment by kemitchell** [comment]
Alas, 'tis a long-standing Firefox SVG rendering bug.

**Comment by iomintz** [comment]
No workarounds?

**Comment by kemitchell** [comment]
I suppose I could render a PNG.

**Comment by Aspie96** [comment]
@kemitchell also the venn diagram is wrong.
