### ISSUE TITLE
What about licence of blog's texts?

### ISSUE THREAD

**Issue by Skabit** [kemitchell/writing.kemitchell.com#32]
Maybe I lost but What is the licence of the blog? (My wish is CC BY-SA or CC BY).

**Comment by kemitchell** [comment]
There is no blog-wide license. What do you want to do?

**Comment by Skabit** [comment]
I found some articles very explanatory and I wanna share they in other media, adapt and modify even make a zine and sell it (remember I'm talkin about free software communities  and underground publishing communities). I'm not lawyer but when an article don't has license I assume that it has a close copyright status.

**Comment by kemitchell** [comment]
You're free to link to my blog, and to share via social media and the like. If you have something more involved in mind, like a zine, send me an email with some details.
